### ISSUE TITLE
CMake build error

### ISSUE THREAD

**Issue by rahul260792** [MaverickTse/softether-install#3]
How to check whether SoftEther VPN service is running or not?
While running the build I had the following error
`./configure: line 28: cmake: command not found`

**Comment by MaverickTse** [comment]
I was unaware of the development branch of SoftEther changed to use CMake. Please wait while I test for fixes.

**Comment by MaverickTse** [comment]
Note that the development branch of SoftEther is being active again, so there may be other breaks coming.

**Comment by MaverickTse** [comment]
FYI, to check status, use ```systemctl status softether-vpnserver ```
